const CONVERSATION_STATE = {
  AWAITING_REGISTRATION_NAME: 'AWAITING_REGISTRATION_NAME',
  AWAITING_REGISTRATION_ADDRESS: 'AWAITING_REGISTRATION_ADDRESS',
  CONFIRMING_ADDRESS: 'CONFIRMING_ADDRESS',
  AWAITING_CATALOG: 'AWAITING_CATALOG',
  SELECTING_PRODUCT: 'SELECTING_PRODUCT',
  AWAITING_QUANTITY: 'AWAITING_QUANTITY',
  PROVIDING_MENU: 'PROVIDING_MENU',
  AWAITING_DELIVERY_ADDRESS: 'AWAITING_DELIVERY_ADDRESS',
  CONFIRMING_ORDER: 'CONFIRMING_ORDER',
};

const IDENTIFICATION_STATES = new Set([
  CONVERSATION_STATE.AWAITING_REGISTRATION_NAME,
  CONVERSATION_STATE.AWAITING_REGISTRATION_ADDRESS,
  CONVERSATION_STATE.CONFIRMING_ADDRESS,
]);

module.exports = {
  CONVERSATION_STATE,
  IDENTIFICATION_STATES,
};
